# backend/interfaces.py

from typing import Protocol

class TokenStorage(Protocol):
    """Contrato para almacenar y recuperar tokens."""
    def load(self) -> dict | None: ...
    def save(self, tokens: dict) -> None: ...

class TokenProvider(Protocol):
    """Contrato para garantizar el suministro de un token válido (Inversión de Dependencias)."""
    def get_tokens(self) -> dict: ...
    def refresh_token(self) -> dict: ...

class TTSEngine(Protocol):
    """Contrato para cualquier motor de Text-to-Speech."""
    def speak(self, text: str) -> None: ...
    def set_volume(self, volume: float) -> None: ... 

class SettingsStorage(Protocol):
    """Contrato para la persistencia de configuración general."""
    def save_bool(self, key: str, value: bool) -> None: ...
    def load_bool(self, key: str, default: bool) -> bool: ...