# backend/interfaces/auth_interfaces.py

from typing import Protocol

class TokenStorage(Protocol):
    """Contrato para almacenar y recuperar tokens."""
    def load(self) -> dict | None: ...
    def save(self, tokens: dict) -> None: ...
    def clear(self) -> None: ...

class TokenProvider(Protocol):
    """Contrato para garantizar el suministro de un token válido (Inversión de Dependencias)."""
    def get_tokens(self) -> dict: ...
    def refresh_token(self) -> dict: ...