# backend\interfaces\i_auth.py

from typing import Protocol

class TokenStorage(Protocol):
    def load(self) -> dict | None: ...

    def save(self, tokens: dict) -> None: ...
    
    def clear(self) -> None: ...

class TokenProvider(Protocol):
    def get_tokens(self) -> dict: ...
    
    def refresh_token(self) -> dict: ...