# backend\interfaces\tts_interfaces.py

from typing import Protocol

class ITTSProvider(Protocol):
    def speak(self, text: str, voice_id: str = None) -> None: ...
        
    def prepare(self, text: str, voice_id: str = None) -> None: ...
        
    def stop(self) -> None: ...

    def set_volume(self, volume: float) -> None: ...
        
    def set_speed(self, speed: float) -> None: ...

    def warm_up(self, voice_id: str = None) -> None: ...

    def get_available_voices(self) -> list[dict]: ...