# backend/interfaces/settings_interfaces.py

from typing import Protocol

class SettingsStorage(Protocol):
    """Contrato para manejar la persistencia de configuraciones de usuario."""
    def save_bool(self, key: str, value: bool) -> None: ...
    def load_bool(self, key: str, default: bool) -> bool: ...
    def save_string(self, key: str, value: str) -> None: ...
    def load_string(self, key: str, default: str) -> str: ...